# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6078e273bbd45cbb011eb0aed52e64453474496bc6703b3f7951fff30bcd4d7b3b4afe88c9013a7cb7b39aa46dbaefc4895f9875b6960bc1ddcfd0088abe9c06

test:
  secret_key_base: 716d3e884248aa3a0a8fe0d5fb684d66084de9bb38259274afa29e95ba947e076e04ce7a50c59445521ee98aaae92e727b0e773306e3678fc5da171957c2caa3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
